# Copyright 2026 Goldman Sachs
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

[package]
name        = "legend-engine-rust-natives-functions-relation"
description = "Runtime native implementations for legend-engine's core_functions_relation Pure extension"
edition.workspace = true
version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
legend-pure-runtime     = { workspace = true }
legend-pure-parser-pure = { workspace = true }
legend-pure-dsl-tds     = { workspace = true }
smol_str                = { workspace = true }
linkme                  = { workspace = true }
im-rc                   = "15.1"
