// Copyright 2026 Goldman Sachs
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! `legend-engine` — engine-flavoured CLI binary.
//!
//! One-line wrapper around `legend_cli::main_entry()`. The interesting
//! work is in the link graph: the `use … as _;` lines below pull the
//! engine extension crates' object files into the binary so their
//! `#[distributed_slice(RUNTIME_EXTENSIONS)]` statics reach
//! `NativeRegistry::discovered()`. Without these `use`s, rustc's
//! linker is free to drop the crates entirely (no other reachable
//! code references them) and `legend build`'s evaluator would silently
//! see an empty extension set.
//!
//! The five `core-functions-*-pure` repo-provider crates' Pure source
//! enters the build via the classpath TOML's `kind = "filesystem"`
//! entries (`legend-pure-classpath.toml` at the workspace root),
//! generated by `cargo gen-classpath`. They carry no
//! `#[distributed_slice]` statics, so no `use` lines for them.
//!
//! Typical invocations:
//! ```bash
//! legend-engine version
//! legend-engine build --classpath legend-pure-classpath.toml \
//!     --format json --skip-tests
//! ```
//!
//! Note: clap's `#[command(name = "legend")]` lives inside the upstream
//! `Cli` struct and isn't overridable. `--help` output says "legend",
//! not "legend-engine". Accepted; see README.

#![forbid(unsafe_code)]
#![allow(unused_imports)]

use legend_engine_rust_natives_functions_relation::RelationFunctionsExtension as _;
use legend_engine_rust_natives_functions_unclassified::FunctionsUnclassifiedExtension as _;

fn main() {
    legend_cli::main_entry();
}
